# Generated by Django 3.0.8 on 2020-07-13 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, default=django.utils.timezone.now, max_length=4000),
            preserve_default=False,
        ),
    ]
